root: true
env:
  browser: true
  node: true
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 2018
extends:
  - '@nuxtjs'
  - 'plugin:nuxt/recommended'
  - airbnb-base
  - 'prettier'
rules:
  no-console: off
  no-constant-condition:
    - error
    - checkLoops: false
  no-param-reassign:
    - error
    - props: false
  vue/comment-directive: off
