root: true
env:
  browser: true
  node: true
  jest: true
parserOptions:
  parser: babel-eslint
settings:
  import/resolver:
    babel-module:
      root: "."
      alias:
        "~": "."
        "@": "."
        "~~": "."
        "@@": "."
extends:
  - '@nuxtjs'
  - 'plugin:nuxt/recommended'
  - airbnb-base
  - 'prettier'
  - 'prettier/vue'
plugins:
  - jest
rules:
  no-console: off
  no-constant-condition:
    - error
    - checkLoops: false
  no-param-reassign:
    - error
    - props: false
  vue/comment-directive: off
