root: true
env:
  browser: true
  node: true
extends:
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:nuxt/recommended'
  - 'prettier'
rules:
  no-console: off
  no-constant-condition:
    - error
    - checkLoops: false
  no-param-reassign:
    - error
    - props: false
  vue/comment-directive: off
